version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backup:/backup
    entrypoint: >
      bash -c "
        mongorestore --drop /backup
        mongod --bind_ip_all 
      "